dataset:
  pixel_values:
    bits_allocated: 'dataset'
    bits_stored: 'dataset'
    rescale_slope: 'dataset'
    rescale_intercept: 'dataset'
    window_centers: [38]
    window_widths: [425]
    photometric_interpretation: 'dataset'
    max_pixel_value: 1
  pixel_spacing:
    current_pixel_spacing: 'dataset'
    new_pixel_spacing: [1.5, 1.5]
  spatial_size: [96, 256, 256]

model:
  model_directory: 'clip_driven_universal_model'
  model_file_name: 'swinunetr.pth'
  model_kwargs:
    img_size: [96, 224, 224]
    in_channels: 1
    out_channels: 32
    backbone: 'swinunetr'
    encoding: 'word_embedding'

inference:
  device: 'cuda'
  amp: True
  threshold: 0.5
